package bernie.greendao.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "BROWSE_ASS_BOOK_MARKS".
 */
@Entity
public class BrowseAssBookMarks {

    @Id
    private Long id;
    private String webSite;
    private String webSiteIcon;
    private String saveDate;
    private String title;

    @Generated
    public BrowseAssBookMarks() {
    }

    public BrowseAssBookMarks(Long id) {
        this.id = id;
    }

    @Generated
    public BrowseAssBookMarks(Long id, String webSite, String webSiteIcon, String saveDate, String title) {
        this.id = id;
        this.webSite = webSite;
        this.webSiteIcon = webSiteIcon;
        this.saveDate = saveDate;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public String getWebSiteIcon() {
        return webSiteIcon;
    }

    public void setWebSiteIcon(String webSiteIcon) {
        this.webSiteIcon = webSiteIcon;
    }

    public String getSaveDate() {
        return saveDate;
    }

    public void setSaveDate(String saveDate) {
        this.saveDate = saveDate;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
