package bernie.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bernie.greendao.dao.BrowseAssBookMarks;
import bernie.greendao.dao.HistoryWebPage;

import bernie.greendao.dao.BrowseAssBookMarksDao;
import bernie.greendao.dao.HistoryWebPageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig browseAssBookMarksDaoConfig;
    private final DaoConfig historyWebPageDaoConfig;

    private final BrowseAssBookMarksDao browseAssBookMarksDao;
    private final HistoryWebPageDao historyWebPageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        browseAssBookMarksDaoConfig = daoConfigMap.get(BrowseAssBookMarksDao.class).clone();
        browseAssBookMarksDaoConfig.initIdentityScope(type);

        historyWebPageDaoConfig = daoConfigMap.get(HistoryWebPageDao.class).clone();
        historyWebPageDaoConfig.initIdentityScope(type);

        browseAssBookMarksDao = new BrowseAssBookMarksDao(browseAssBookMarksDaoConfig, this);
        historyWebPageDao = new HistoryWebPageDao(historyWebPageDaoConfig, this);

        registerDao(BrowseAssBookMarks.class, browseAssBookMarksDao);
        registerDao(HistoryWebPage.class, historyWebPageDao);
    }
    
    public void clear() {
        browseAssBookMarksDaoConfig.clearIdentityScope();
        historyWebPageDaoConfig.clearIdentityScope();
    }

    public BrowseAssBookMarksDao getBrowseAssBookMarksDao() {
        return browseAssBookMarksDao;
    }

    public HistoryWebPageDao getHistoryWebPageDao() {
        return historyWebPageDao;
    }

}
